import Head from "next/head";
import { Inter } from "next/font/google";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by Parteek Kumar" />
        <meta name="keyword" content="nextjs, parteekblog, nextjsblog" />
      </Head>

      <div className="mainnav">
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </div>

      <div className="container">
        <div className="title-blog">
          <h1>Hello Everyone</h1>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn javascript for beginners?</h3>
            <p>Javascript is a language used to design logic for web </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript for beginners?</h3>
            <p>Javascript is a language used to design logic for web </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript for beginners?</h3>
            <p>Javascript is a language used to design logic for web </p>
          </div>
        </div>
      </div>
    </>
  );
}
