import Head from "next/head";
import { Inter } from "next/font/google";
import Script from "next/script";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by Parteek Kumar" />
        <meta name="keyword" content="nextjs, parteekblog, nextjsblog" />
      </Head>

      <div className="container">
        <div className="title-blog">
          <h1>Hello Everyone</h1>
        </div>
      </div>
    </>
  );
}
